# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Report an issue
description: Report an issue to help improve the library
labels: need-triage

body:
- type: markdown
  attributes:
    value: |
      **Your help in making Warp-NN better is greatly appreciated!**

      * Please ensure that:
        * The issue hasn't already been reported by using the [issue search](https://github.com/NVIDIA/warp-nn/search?q=is%3Aissue&type=issues).
      * For questions, please consider [open a discussion](https://github.com/NVIDIA/warp-nn/discussions).
      <br>

- type: textarea
  attributes:
    label: Description
    description: A clear and concise description of the issue/bug. Try to provide a minimal example to reproduce it.
    placeholder: |
      Markdown formatting might be applied to the text.

      ```python
      # use triple backticks for code blocks or terminal output/error messages
      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Diagnostic information
    description: |
      Provide some details about your environment, such as the Warp version, Python version, and OS.
      Run and paste the output of the command: `python -c "import warp_nn; warp_nn.print_diagnostics()"`
  validations:
    required: false
